### ISSUE TITLE
Sand doesn't drop after explosion

### ISSUE THREAD

**Issue by mmlmml1** [PocketMine/PocketMine-MP#2735]
Sand or gravel doesn't drop after explosion

**Comment by WhiteWolfOwner** [comment]
I think why the sand does not drop is because of the lag that the tnt causes when it explodes. It kind of freezes the sand or gravel in place. But when you break or place a block beside it, it will all fall. I think if you report this to @shoghicp He should add it to the TODO list. 
:)

Thanks,
WhiteWolfOwner

**Comment by PEMapModder** [comment]
@whitewolfowner and isn't he reporting this now...

**Comment by WhiteWolfOwner** [comment]
I have other things to do... Quit going around and picking out my mistakes. I am trying my best to help people with my knowlage of Minecraft...

**Comment by WhiteWolfOwner** [comment]
@PEMapModder

**Comment by PEMapModder** [comment]
@WhiteWolfOwner this is a _bug tracker_ not a _help forum_. You don't help people here. And you said "report to @shoghicp", which he is already doing. And I didn't go around picking on your mistakes. I watched this repository and received notifications when someone comments, and your comments that aren't what should be here are annoying us 156 watchers of this repo. Read the contribution guidelines.
