### ISSUE TITLE
If the server is a long operation, Corrupted chunk detected

### ISSUE THREAD

**Issue by HmHmmHm** [PocketMine/PocketMine-MP#2741]
![1241241](https://cloud.githubusercontent.com/assets/8337568/6365116/f99e15c4-bcf4-11e4-8998-0a3e655f7c1e.png)

![14](https://cloud.githubusercontent.com/assets/8337568/6365150/8b1b8158-bcf5-11e4-91df-b568f8e1a775.png)
![17](https://cloud.githubusercontent.com/assets/8337568/6365149/8b1a3e1a-bcf5-11e4-982e-2c72ffef6ae6.png)

i'm using McRegion map and
PocketMine-Soft 238.

(it is 24 time server, always openning)

in the first boot everything is fine,
but after a lot of time (maybe 2day ~ 4day ago),
some chunk is overlapped generated ..

this error is extremely deadly...

how i can prevent or
stopping the generate overlap chunk?

![default](https://cloud.githubusercontent.com/assets/8337568/6365212/9c657f94-bcf6-11e4-88a2-b2be71e3979c.png)

**Comment by 64FF00** [comment]
Duudeeeee Try using ASR by @iJoshuaHD

**Comment by HmHmmHm** [comment]
@64FF00 I aleady using for something my auto reload&reboot plug-in, (it's same ASR)

**Comment by HmHmmHm** [comment]
aww.. i still have this problem..
why...why! corrupted chunk detecting??
![111111](https://cloud.githubusercontent.com/assets/8337568/6373431/f80251d6-bd4d-11e4-846d-546077e697ae.png)

**Comment by iVertx** [comment]
I have the same issue:

![screenshot_2015-02-27-11-13-07](https://cloud.githubusercontent.com/assets/10237969/6424045/32a8b79e-becf-11e4-9b8b-298b571cb81e.png)
![screenshot_2015-02-27-12-50-50](https://cloud.githubusercontent.com/assets/10237969/6424051/40d63062-becf-11e4-83ff-c9e79741f8b3.png)

I did everything possible to solve this problem but nope... (Forget convert from Anvil to mcregion an vice-versa, this bug isn't related to it)
Man, it will simply destroy your map completelly like my map... And my map have other major bug like these = massive tree generations... I got tree walls in every grass block in my server, basically i can't build anything more in my map, because every, every and EVERY time i need to rebuild overlaped chunks and cut off trees... Really a dedly error in pocketmine

**Comment by iVertx** [comment]
Captured this morning:

![screenshot_2015-02-27-23-03-45](https://cloud.githubusercontent.com/assets/10237969/6427177/b51dd1c2-bf57-11e4-96c4-05550927e4d2.png)
![screenshot_2015-02-28-11-14-00](https://cloud.githubusercontent.com/assets/10237969/6427179/c029ed1c-bf57-11e4-8e79-3f77ffe066a4.png)
![screenshot_2015-02-28-11-27-12](https://cloud.githubusercontent.com/assets/10237969/6427181/c9fa4a1c-bf57-11e4-834a-75d52514cc15.png)

(--')

**Comment by HmHmmHm** [comment]
I actually solved this problem,
i developed a plug-in to the 'backup/restore' chunks

If someone is suffering from this problems,
check our development team(for pocketmine) and share problems
https://github.com/if-Team/PMMP-Plugins/blob/master/IDEA/src/IDEA/IDEA.php

**Comment by iVertx** [comment]
Hm, how this plugin works? It auto restore chunks after detect corruptions? Or i need to type commands to restore? Thx

**Comment by shoghicp** [comment]
This might have been fixed by #2771
Please comment here if not fixed
