### ISSUE TITLE
"moved" wrongly possibly fix

### ISSUE THREAD

**Issue by vvzar** [PocketMine/PocketMine-MP#2799]
Can You please change line in file src/pocketmine/Player.php:
1360             -		if($diffY > -0.5 or $diffY < 0.5){
1360             +         if($diffY >= -0.5 or $diffY <= 0.5){ 

I think, this way stairs and other thin blocks will not generate  "moved wrongly" issue :(

**Comment by shoghicp** [comment]
oh. Well, now we only need to fix the thin vertical blocks like iron bars or glass panes, they are wrong. Also fences.

I'll check this tomorrow, I can't test right now!

**Comment by matcracker** [comment]
Nice thing!

**Comment by thelucyclub** [comment]
#2778

**Comment by PEMapModder** [comment]
Make a pull request.

**Comment by shoghicp** [comment]
This does not fix the issue. Helps with detecting a problem, but without proper offset checks it's not useful. I've been experimenting with some other settings, but it'll be for 1.5

**Comment by thelucyclub** [comment]
This would be a great fix to #2778.
Heres another way to fix it:
=======================
###### Code (Copy & Pasted):
`You can turn that off in pocketmine-soft.yml (if running pm-soft).
This because the movement player movement on slab is not registered correctly with pocketmine, this means the server will warn that {player} moved wrongly. PocketMine should be updated soon to fix this. :hankey: 
The way to fix this is to turn off check-movement in pocketmine-soft.yml (if using pm-soft), or tell your players to simply JUMP over on to the slab. Hope I helped! :smile:`

**Comment by vvzar** [comment]
The reason i decided to provide this - in playing experience. While i moving up too slow on stairs  "revert" doesnt happen. So I tried removing half-block distance the same as one stair from expression by giving to such movement zero speed. 
Sorry for empty hope

**Comment by shoghicp** [comment]
@vvzar The fix is correct, but doesn't fix all the things. It's only the first part :)

**Comment by thelucyclub** [comment]
:smile:

**Comment by tyan-boot** [comment]
it is a serious problem,hope for fixing it soon

**Comment by vvzar** [comment]
in dev 1.5 builds warning seems to be fixed.
New possible mistake in height of mob or height between 2 blocks, or damage count. When i place mob citizen on carpet and above him roof of blocks - mob takes damage every second. Like inside wall or block.

**Comment by vvzar** [comment]
Maybe we can count height of mob > 2 blocks == 2 blocks?
