### ISSUE TITLE
/heal error

### ISSUE THREAD

**Issue by Shamil0402** [PocketMine/PocketMine-MP#2988]
00:51:26 [INFO] Usage: /heal <player>
heal springtrap
00:51:35 [INFO] An unknown error occurred while attempting to perform this command
00:51:35 [CRITICAL] Unhandled exception executing command 'heal springtrap' in heal: Argument 2 passed to pocketmine\entity\Living::heal() must be an instance of pocketmine\event\entity\EntityRegainHealthEvent, none given, called in phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/plugins/EssentialsPE.phar/src/EssentialsPE/Commands/Heal.php on line 39 and defined
00:51:35 [NOTICE] InvalidArgumentException: "Argument 2 passed to pocketmine\entity\Living::heal() must be an instance of pocketmine\event\entity\EntityRegainHealthEvent, none given, called in phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/plugins/EssentialsPE.phar/src/EssentialsPE/Commands/Heal.php on line 39 and defined" (E_RECOVERABLE_ERROR) in "/src/pocketmine/entity/Living" at line 78

**Comment by LDX-MCPE** [comment]
This crash was caused by [EssentialsPE](https://github.com/LegendOfMCPE/EssentialsPE), not PocketMine. Do not report plugin problems in the PocketMine repository. Please read the [contribution guidelines](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before opening issues.
