### ISSUE TITLE
New version of Minecraft Pocket Edition cannot find Pocketmine servers

### ISSUE THREAD

**Issue by pcapazzi** [PocketMine/PocketMine-MP#3105]
Previous version 0.10.4 could find my local pocketmine server. Upgraded to MCPE 0.11.1 and server is not showing up in list and I cannot connect to it using my IP address. I noticed this on my iPhone first (new version was installed automatically) and was able to still see it with my iPad. When I upgrade the iPad I could not see the server anymore. Again I tried connecting directly with the iPad by IP and port and that did not work as well. 

The Development Build does show up and I am able to connect. Gameplay is not as smooth though. Current Production version was better in that respect (IMO). I tried Beta and that did not work. I suppose this is server agnostic but just in case I'm running this on Mac OS X Yosemite.

**Comment by sirxon** [comment]
I would like to second the above issue.  My IPad and Samsung cannot connect but the Nook detects the pocketmine server automatically and the Nook has not been updated yet.  The pocketmine server shows nothing when the IPad tries to connect and 'list' shows no one is connected but when I hit cancel or timeout on the IPad the server notes the IPad's address has "logged out due to disconnect/timeout."

**Comment by andyvanee** [comment]
Same issue here, though my server is running on a Digital Ocean droplet. 0.10.4 was working fine. I upgraded my Nexus 4 to `v0.11.0 alpha` and then upgraded PocketMine to the latest version and it just hangs on the `Locating Server` page.

PocketMine-MP version 1.4.1-980 「絶好(Zekkou)ケーキ(Cake)」 (Implementing API version 1.11.0 for Minecraft: PE v0.10.5 alpha protocol version 20)

When I type `list` in the console, it shows 0/20. If I then press 'Cancel' on my phone, the server actually logs the disconnect, so it's not totally unreachable.

```
list
22:42:54 [INFO] There are 0/20 players online:
22:43:16 [INFO] [/70.72.140.73:33110] logged out due to client disconnect
```

BTW, thanks for the great project! My daughter and I have been having lots of fun with it :)

**Comment by markkrueg** [comment]
Only the development version supports MCPE 0.11.x, so you MUST use version 990 or newer. You will notice a 1.5 in the name; and that is what tells you it is 0.11.x compatible.

**Comment by andyvanee** [comment]
Aha, thank you! Looks like my issue is that I didn't read :( I had used the previous installation instructions, which gives incompatible versions?

`wget -q -O - http://get.pocketmine.net/ | bash`

Produces a broken installation.

`curl -sL https://raw.githubusercontent.com/PocketMine/php-build-scripts/master/installer.sh | bash -s - -v development`

This works. I had removed the bash options, because that's what I had in my bash history, and I had assumed that 1.4.1 was a production release, not a development release.

**Comment by shoghicp** [comment]
1.4.1 is a production release, 1.5 is still in development.

**Comment by andyvanee** [comment]
Hmm, ok. I guess I'm confused about version numbers. Sorry about that!

I do know that my install one week ago, using the recommended Linux command, produced a working version. The same command today produces a non-working version.

Using the `development` flag, things are working now.

`This server is running PocketMine-MP version 1.5dev-1208 "活発(Kappatsu)フグ(Fugu)" (API 1.12.0)`

**Comment by shoghicp** [comment]
MCPE gets updated, and with it it has network protocol changes. That means that new versions of the game won't be able to connect to old versions of PocketMine

**Comment by andyvanee** [comment]
Ok, Thanks!
