### ISSUE TITLE
§ signs and the letter code after them take up space

### ISSUE THREAD

**Issue by AndreyNazarchuk** [PocketMine/PocketMine-MP#3159]
When writing a sign and using a § sign and a code after it, for example §a, it takes up a lot of space on the sign. This is bad because only about half of the line can then be used.

I suspect that this is also the case with messages, and this would cause them to be counted wrongly.

Please fix,as this is not allowing people to write what they want on signs, which are limited as they are. 

Thank you!

**Comment by shoghicp** [comment]
This is a limit on MCPE and not PM, and it works like this on PC

**Comment by AndreyNazarchuk** [comment]
Why do you hate me? This is a bug.

**Comment by PEMapModder** [comment]
There is no hate involved.
This is an MCPE issue, and it is not related to PocketMine.

**Comment by AndreyNazarchuk** [comment]
Well you can fix it can't you? Its not good that if I use colors and bold I
can only put 9 chars instead of the usual.

**Comment by sekjun9878** [comment]
Hello @AndreyNazarchuk, please continue discussion on our IRC channel if you want further discussion. This issue is a limitation of the MCPE client, and the PocketMine software in general follows what MCPE / MCPC / Bukkit does as convention. Which means there is *nothing* we can do to fix this issue. There may be a plugin to resolve this issue, however. Locking discussion as issue is not a bug.
