### ISSUE TITLE
Feature proposal to add more featureful, advanced commands beyond the ones supported by default Bukkit

### ISSUE THREAD

**Issue by sekjun9878** [PocketMine/PocketMine-MP#3222]
This is a proposal to add more featureful commands to the default PocketMine installation. This will allow advanced management of a PocketMine server both on console and remotely, without any additional unnecessary plugins.

This option will be able to be disabled in pocketmine.yml for users that need backwards compatibility (although this should not be BC breaking). This will be enabled by default.

The additional commands will be distinct from the current set of commands (referred to as PC Vanila Server commands) and will be implemented with new command names, therefore there should be no backwards compatibility breaking change.

As an example, these are currently settings that cannot be retrieved or manipulated by the default set of commands.

- Getting a player's IP address (/ip)
- Getting / setting the name of the server (/motd)
- and more

In addition, these will be beneficial commands to have
- Inspecting a player's inventory (/inspect)
- Getting a player's coordinates (/coord)
- The /status command should be opt-out instead of opt-in. There is no reason for this command to be hidden from the ops.
- and more

Discuss below.

**Comment by Thunder33345** [comment]
Cool
is it possible to re-add self telling?(allow /tell <yourname>)

**Comment by shoghicp** [comment]
You don't need to get the IP address of an user to ban him. Just do /ban-ip <player name>

Also, this can be bundled as a plugin directly. A lot of the commands you posted here are implementation-dependent (example, inspecting inventory may not work on all platforms).
The commands shipped by default are there for *basic* administration and using the basic Minecraft features. Coord is not useful, as you can teleport to a player and you would not want to do that except if the player itself wants to see it (at that point this is not a server and just a single player world that runs on a different system).

If you add /motd, people will want to modify all the settings everywhere, this is not possible.

**Comment by shoghicp** [comment]
Also, 1.5 is due to release in a few days. Please don't add stuff that is not needed or critical into that milestone.

**Comment by RandomAltThing** [comment]
•/ip can be done in plugins (Like EssentialsPE, its /seen)   
•/inspect can be done in plugins (There is this one plugin with /invsee which places the contents of the targets' inventory into your until you do another command)

•We need a /achievement command! I would make a PR with it but I'm only familiar with the plugin method of 
<pre>
public function onCommand(CommandSender $sender, Command $cmd, ArrayList $args){

}
</pre>
Or whatever it is. I can't quite remember the parameters.

•We need a command for teleporting to spawn because on servers with no plugins it is hard to get back to spawn. This is how you would do it in a plugin:
<pre>
case "spawn":
    $sender->teleport($sender->getServer()->getDefaultLevel()->getSpawnLocation());
  $sender->sendMessage(TextFormat::YELLOW ."Teleporting to spawn...");
    break;
</pre>

/spawn would not be hard to implement.

•Maybe /gamerule ? This would be SO useful. Such as */gamerule displayJoinMessages false*. In a plugin this could be:
<pre>
public function onPlayerJoin(PlayerJoinEvent $e){
//Obviously you would need an IF statement
$e->setCancelled(true);
}
</pre>
I have tested the above and it works, blocks join messages.

• Maybe a new alias for /tell, /m. It is used by many people.

• Possibly more arguments in commands such as /tell /kill etc. With the use of @e, @p, @r etc. This would make it easy to kill everyone on the server, kick everyone, or /tell everyone a message. Basically all commands that needs to specify the target player could use one of the above - just like in PC.

**Comment by JoahDave** [comment]
Aww shoghicp, why you say no!

**Comment by sekjun9878** [comment]
Jesus, no need to be so defensive... How about 1.6 then? Thanks for your "consideration" regarding this matter.

**Comment by PEMapModder** [comment]
@RandomAltThing all that you mentioned should  be done with plug-ins.  Except /gamerule,which is in the TODO list already.

**Comment by RandomAltThing** [comment]
@PEMapModder No, I only know how to add it using plugins so I was using it as an example of what it would look like so it can be interpreted into pocketmine.

**Comment by Thunder33345** [comment]
@shoghicp will do it on 1.6 1.7 1.8 1.9 1.9.1 1.9.2 .......
