### ISSUE TITLE
scheduleRepeatingTask not cancelling

### ISSUE THREAD

**Issue by hoyinm14mc** [PocketMine/PocketMine-MP#3328]
I used all correct method to cancel repeatingtask, but it just ignore the cancel code, always continue to run.  Fix that pls

**Comment by PrimusLV** [comment]
You probably did something wrong cuz works for me good.

**Comment by sekjun9878** [comment]
Sample code please? Possible link to #3346.

**Comment by legoboy0215** [comment]
Me too. I tried to cancel it too. Now I only can cancel it with cancelTasks($this)

**Comment by iksaku** [comment]
There's only one way to cancel tasks... But you may be using an incorrect one:
* ***Incorrect***:
```php
$task = new Task(); // This will change depending on your task class, but I will just use it as a reference
$this->getServer()->getScheduler()->scheduleRepeatingTask($task, 10); // Again, just example...
// MOAR Code
$task->cancel();
```
**Correct*:
```php
$task = new Task();
$this->getServer()->getScheduler()->scheduleRepeatingTask($task, 10); // Again, just example... Your "Task" class will change this text...
// MOAR Code
$this->getServer()->getScheduler()->cancelTask($task->getTaskId());
```

=

But why is this!?!?!?!?!?!
Due to the class stored by the `$task` variable... In the first example, the "incorrect" one... You're storing a type of `Task()` class, while in the second one we are using the 
Due to the class being used to cancel the task... the incorrect way is to use the type of `Task` or `TaskHandler`, you must use the `ServerScheduler` because is the manager for all the tasks
