### ISSUE TITLE
Uninitialized string offset: -1 File: /src/pocketmine/level/format/mcregion/Chunk__64bit Line: 121

### ISSUE THREAD

**Issue by Awzaw** [PocketMine/PocketMine-MP#3500]
I'm getting about 50 crashes a day with this error on 3 servers with about 40 players each on most of the time. Players are always at y<=1 when it happens, and the chunk in questions seems to contain blocks that allow users to fall through them into the void. I'm running 3 servers on maps that had no issues in 1.5, and they all have the same problem with 1.6dev builds.

If players spawn to the XYZ in question the server crashes, but when you visit the XYZ without spawning there, it doesn't crash every time, but things get strange.

CrashDump: http://pastebin.com/Xx2QmQyC
Video: of MCPE behaviour at the problem XYZ: https://youtu.be/3JwOITjPGXE

**Comment by McDrakon123** [comment]
I used to get that error now all i get is http://pastebin.com/aBG11w58

**Comment by reidq7** [comment]
I have this too. It's really quite terrible and I'd probably sacrifice my soul for a fix to this.

**Comment by McDrakon123** [comment]
Well i wouldnt go THAT far but i get what you mean, i got 126 crash reports over like 2 days

**Comment by reidq7** [comment]
I probably got triple that. I just want my server to WORK and software to work and people to stop ddosing me and hacking op and all this crap that comes with a top 3 server.

**Comment by LouisBHirst** [comment]
(sorry i know this isn't a forum) Reid totally get your frustration, and
remember that PocketMine is a free gift from the PM team and at the end of
the day we have to feel lucky that it works at all.  Sure I'd give my left
nut to have a PM version completely uptodate with all feature & functions
running perfectly, but that's totally unrealistic given the situation and I
don't think it would be as good anyway because something that big would be
run by a monolithic company that wouldn't care about it's users.  These are
really exciting (albeit unstable at times) in the evolution of PE / PM and
and we have to "suck it up" just look at the PHP7 update coming, now that's
really cool, can you believe PM is propelling PHP forward?  how cool is
that!

Bart Hirst
(484) 802-4798
http://www.linkedin.com/in/louisbhirst

**Comment by reidq7** [comment]
Thanks for reminding me of that. It's true. Thanks pocketmine :) m

**Comment by Yosshi999** [comment]
I think this is the reason (y=9.99 ... < 10)
![screen20150919](https://cloud.githubusercontent.com/assets/8027142/9976614/ae993e32-5f24-11e5-82ce-761befb3fc2d.png)

**Comment by jazzwhistle** [comment]
AlwaysSpawn works around the problem, or there's a PHP script to fix the player .dat files on this thread:
https://forums.pocketmine.net/threads/mcpe-0-12-x-compatible-pocketmine.11094/page-9#post-117011

**Comment by wrewolf** [comment]
same http://pastebin.com/nyy3MWEx

**Comment by dktapps** [comment]
This has long since been fixed on PMMP's PocketMine-MP.
