### ISSUE TITLE
Trouble with the /give Command

### ISSUE THREAD

**Issue by pmicznik** [PocketMine/PocketMine-MP#3637]
Sometimes I have problems with the /give command. For instance, when I type /give MCstar777 Diamond Sword in chat, responds: “given MCstar777 Diamond [item id] x 0”. I also tried typing “/give MCstar777 Diamond Sword x 1” and the response is that there are some syntax errors.

My server is running on PocketMine-MP and MCProHosting

**Comment by PEMapModder** [comment]
The item names can be found at [Item.php](../blob/master/src/pocketmine/item/Item.php) (case-insensitive, e.g. `diamond_sword`). Keep in mind that in PocketMine commands, `<parameter>` usually means that a value with no spaces is expected.
Also, please check the usage of /give. There is no `x`.

Therefore, the command should be `/give mcstar777 diamond_sword 1`. Throwing errors about incorrect usage is expected PocketMine behaviour, and this issue is invalid.
