### ISSUE TITLE
Client stuck in Generating world / locating server

### ISSUE THREAD

**Issue by guszedd** [PocketMine/PocketMine-MP#3771]
In top bar of server shows a user connected, but when use command "list" still shows 0/20 users connected. When hit cancel on client the server logs a disconnect. The world never loads on the client. Simple install of server. Not sure what to do.

**Comment by tiNsLeY799** [comment]
When a world first generates, it is most likely in mcanvil, a type of MC
world file. Anvil is infamous for being buggy and slow OR it could be the
amount of chunks the server processes each tick. I use mcr (region) because
it is much faster than anvil BUT it takes black grass as an effect from the
world folder not knowing what color grass it is.

**Comment by PEMapModder** [comment]
It appears that you are using an old server version. When the server starts, does it say server software for 0.11?

**Comment by guszedd** [comment]
You are correct. Updated the phar and now it will connect.
