### ISSUE TITLE
server random crashes 

### ISSUE THREAD

**Issue by cfoti420** [PocketMine/PocketMine-MP#3883]
[CrashDump_Sat_Jan_16-15.45.34-EST_2016.txt](https://github.com/PocketMine/PocketMine-MP/files/93099/CrashDump_Sat_Jan_16-15.45.34-EST_2016.txt)

**Comment by HmHmmHm** [comment]
Allowed memory size of 536870912 bytes exhausted (tried to allocate 332889 bytes)
It means you need more RAM in your devices. it is not pocketmine problem.

**Comment by dterweij** [comment]
No, PM and most of its clones does have this problem. Is not a RAM problem.
There is something that is doing a lot cycle/tick loops that is eating memory.
This kind of thing started since 0.13.1 and is reported a lot. Many developers says, not PM problem, use more RAM. Thats kind of bully and easy to say. There is realy a nasty bug in there that needs to debugged.

**Comment by robske110** [comment]
#592

**Comment by cfoti420** [comment]
Jesus I have 2 gigz of ram in the machine. I'll just have to disable X 
thank you.


chris

Sent with AquaMail for Android
http://www.aqua-mail.com
