### ISSUE TITLE
Player Blocking

### ISSUE THREAD

**Issue by Samueljh1** [PocketMine/PocketMine-MP#3985]
Since the update, RakLib has been blocking players all day when crafting, using items and generally doing most things. It seems a lot of packets have been broken / need updating.

**Comment by PEMapModder** [comment]
Player blocking is caused by PocketMine internal exceptions, which may not be related to packets at all. They only mean that a non-plugin error occurred while handling a packet.

This issue is too vague, and covers a lot of already-reported and shall-be-reported issues. Please, set `debug.level` to 2 in pocketmine.yml to see what exceptions these are, and report them accordingly.
