### ISSUE TITLE
Please advise how to help connect ipad to PocketMine server

### ISSUE THREAD

**Issue by mlwiles** [PocketMine/PocketMine-MP#4167]
### Issue description

I have looked at others that posted similar questions and I have not found any solution to my issue.
I have installed on Windows 8 - PocketMine-MP 1-1980
I have have been asked by my son to help him get this working so he can play with friends outside of the house .. but first I wanted to make sure that we are able to connect to the server directly.
So we have shut down all firewalls (*I feel naked*)
We are using iOS MineCraft PE v0.14.2
When having both the PC and the iPad on the same internal network 192.168.1.x ... we are getting the message "unable to connect to world"
I have verified that the server is listening on the default port 19132.
I am completely new to Minecraft PE ... spent lots of time helping with Mods on Minecraft Full version ... 
Just looking for some advice on where to look at logs, trace, etc.

Sorry for the noob request .. I am a software engineer but dont have time for the gaming life anymore as I am a father and work and blah.

Thanks for your help and please let me know what other information I can provide to get more assistance.

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* OS:

### Crashdump, backtrace or other files

* ...

**Comment by TheIcyStar** [comment]
First off, I advise you to use the [pocketmine forums](https://forums.pocketmine.net/forums/help/) for help, the pocketmine github page is more for tracking bugs instead of help requests.

Now, for the actual help:
Right now, the patch for 14.2 is being developed, and a simple version bump doesn't work, as noted in #4153 , 
**BUT** when you are able to get **the correct** .phar file update for 0.14.2, here is what you have to do:
Download and replace the PocketMine-MP.phar file with the new one. (remember to rename it to PocketMine-MP.phar !)
Then, update the PHP binaries to PHP7. [they can be found here](https://bintray.com/pocketmine/PocketMine/).
Open the downloaded file as an archive (using 7zip or winrar) and extract the new PHP files and replace the old php files.

ps: if you have any error after updating the phar and php files and then starting the server (something like "bin\php\php.exe exit 127 missing file (OR) missing directory (OR something like that)", Open up bin>php>php.exe and google the error, you are most likely missing some .dll file. DO NOT DIRECTLY DOWNLOAD A .DLL FILE, **You have to use some installer** to properly fix this missing .dll problem (most likely some microsoft distributable).

**Comment by mlwiles** [comment]
Thank you TheicyStar ... my apologies for going GitHub route, other search results didnt seem very useful, you gave me lots of pointers and I will note them for future.
