### ISSUE TITLE
PocketMine Float Error

### ISSUE THREAD

**Issue by ucrogamer** [PocketMine/PocketMine-MP#4247]
### Issue description

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar://C:/Users/uCro Group/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php on line 80
### Steps to reproduce the issue
1. ... Start PocketMine
### OS and versions

- PocketMine-MP: 1.6
- PHP: 7.0
- OS: Windows 10 Home

**Comment by Survingo** [comment]
That's an invalid issue. Try updating plugins, using right PocketMine-MP version and PHP version

**Comment by PrimusLV** [comment]
The error lays inside PocketMine code, try updating.

**Comment by ChrisFWood** [comment]
To call this an invalid issue is sorry to say is invalid, there is a bug here.

While I am running Linux that is not relevant to the issue as it affects all OSes.

The issue is simple if you start from clean and install the current stable version it may not work without effort from the user.  This is because the installed stable 1.4.1 PocketMine-MP.phar file is for one version of php (5.6.10) and the startup.sh (I assume the windows one as well) installed is geared for another version of php (7.0.?), to the point if php 7 is installed it will use that and if not found tells the user to install it "Couldn't find a working PHP 7 binary, please use the installer.".  Now sure it might work for some new users, but trying to find the answer took more effort that it should because of the answers given, or a basic shut down / failure to acknowledge the issue, hopefully this helps people that follow me.

The solution hinted at to install development version but that kind of defeats the point of the stable version.  Alternatively you can use the -p to inform startup.sh (guess other OSes will have the same switch else you need to force the right version of php) to use php 5.6.10.  The true bug fix is get the installer script to download appropriate startup.sh script for the version of phar file downloaded, or make a stable version for php 7.0.

**Comment by LegendIsCool** [comment]
Fatal error: Cannot use pocketmine\level\generator\Void as Void because 'Void' is a special class name in phar://C:/Users/ELiot/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php on line 63 how Do i fix this
