### ISSUE TITLE
Items Not Showing For Leet Servers! 

### ISSUE THREAD

**Issue by princess9989** [PocketMine/PocketMine-MP#4353]
Well. I found out that we weren't allowed to use water and lava etc. so I bought the 'unban' plugin with my credits that I bought. So I thought that would also allow me to spawn different animals. Such as wolves, ocelots, horses, etc. but that doesn't work, along with other items that came along with the previous updates that cannot be found on a leet server. Please enable us to spawn different animals, and allow us to place down other fun items throughout the updates Minecraft has to offer! It would be much Appreciated.

I use IOS. 
I use Leet.severs (they said their ran by pocket mine)
Please allow paintings, spawners, etc.

**Comment by robske110** [comment]
To clarify: Leet.cc is a hosting company. It hosts this software, which itself is a free software, made by devs who are spending their free time on this project. Leet.cc is in no relationship with this project.
AIs are not implemented yet and spawning animals with spawn eggs is "disabled" because they wouldn't move anyways. Other items being blocked is purely done by leet.cc and their attempt to make server hosting costs less by banning "cpu-intensive" items. You can host.

**Comment by MetalMinurz** [comment]
Pocketmine currently does not support mobs and animals. They plan to release that in the future.
