### ISSUE TITLE
UBUNTU SERVER: [ERROR] Unable to find the pthreads extension. and [ERROR] Please use the installer provided on the homepage.

### ISSUE THREAD

**Issue by Eralgonius** [PocketMine/PocketMine-MP#449]
UBUNTU SERVER 11.10 TERMINAL:
<i>root@ramil:~/lol# ./start.sh
05:33:48 [ERROR] Unable to find the pthreads extension.
05:33:48 [ERROR] Please use the installer provided on the homepage.
Press [Enter] to continue... </i>

**Comment by konsumer** [comment]
Yeh, I followed the directions on Ubuntu 16.04.3, they don't work.

The install script doesn't even install the correct local version of PHP (5 instead of 7), and the setup script doesn't set it's env variables correctly, so I'm pretty sure this wouldn't work for anyone.

```sh
sudo apt install perl gcc g++ make automake libtool autoconf m4 gcc-multilib
wget -q -O - http://get.pocketmine.net/ | bash
[*] Found PocketMine-MP Final_1.4.1 (build 980) using API 1.11.0
[*] This stable build was released on Tue Mar 17 17:00:47 UTC 2015
[+] The build was signed, will check signature
[*] Installing/updating PocketMine-MP on directory ./
[1/3] Cleaning...
[2/3] Downloading PocketMine-MP Final_1.4.1 phar... done!
[*] Checking signature of PocketMine-MP.phar
gpg: Signature made Tue 17 Mar 2015 05:16:17 PM UTC using RSA key ID A7837F89
gpg: Good signature from "Shoghi Cervantes <shoghicp@gmail.com>"
gpg:                 aka "keybase.io/shoghicp <shoghicp@keybase.io>"
[+] Signature valid and checked!
[3/3] Obtaining PHP: detecting if build is available...
[3/3] Linux 64-bit PHP build available, downloading PHP_5.6.10_x86-64_Linux.tar.gz... checking... regenerating php.ini... done
[*] Everything done! Run ./start.sh to start PocketMine-MP

./start.sh 
Couldn't find a working PHP 7 binary, please use the installer.
```

So,  installed the ubuntu's php7:

```sh
sudo apt install php7.0-cli
```

ran it again:

```sh
./start.sh 
Couldn't find a working PHP 7 binary, please use the installer.
```

Ugh. annoying. Doesn't seem to be detecting php. Added this line to start.sh:

```sh
PHP_BINARY=`which php`
```

Run it again, I get this:

```sh
./start.sh 
[CRITICAL] Unable to find the pthreads extension.
[CRITICAL] Please use the installer provided on the homepage.
```

installed pthreads:

```sh
sudo apt install libevent-pthreads-2.0-5
```

Same error, after.

Since it install php5, even though it's looking for php7, I tried using local php5:

```sh
PHP_BINARY="./bin/php5/bin/php"
```

This made it work, but it doesn't work if you follow the directions.

**Comment by robske110** [comment]
You‘re on the wrong repo and you are using the wrong command/hostname. This repo is dead, and still is php5. The correct command for pmmp is: `wget -q -O - https://get.pmmp.io | bash -s -`
This command should install everything needed and ./start.sh should start the server :)
The new install docs: http://pmmp.readthedocs.io/en/rtfd/installation.html

**Comment by konsumer** [comment]
@robske110 Aha! Thanks.
